

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Mofokeng
 */
public class IPUI extends javax.swing.JFrame {

    /**
     * Creates new form IPUI
     */
    public IPUI() {
        initComponents();
        fileHandler = new FileHandler();
        ipValidator = new IPValidator();
        this.setVisible(true);
        this.myInitComponents();
        this.setLocationRelativeTo(null);
    }

    public static void main(String[]args)
    {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        new IPUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaInvalidList = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaValidList = new javax.swing.JTextArea();
        btnAbout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaMasterList = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnOpenFile = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbCurrent = new javax.swing.JRadioButton();
        rbAlt = new javax.swing.JRadioButton();
        btnExport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaInvalidList.setEditable(false);
        areaInvalidList.setColumns(20);
        areaInvalidList.setRows(5);
        jScrollPane1.setViewportView(areaInvalidList);

        areaValidList.setEditable(false);
        areaValidList.setColumns(20);
        areaValidList.setRows(5);
        jScrollPane3.setViewportView(areaValidList);

        btnAbout.setText("About Delevoper");

        jLabel1.setText("Invalid IP Addresses");

        jLabel2.setText("Valid IP Addresses");

        areaMasterList.setEditable(false);
        areaMasterList.setColumns(20);
        areaMasterList.setRows(5);
        jScrollPane2.setViewportView(areaMasterList);

        jLabel3.setText("IP Addresses");

        btnOpenFile.setText("Open File");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Exort Output Files"));

        rbCurrent.setText("Export To Current Folder");

        rbAlt.setText("Export To Alternate Folder");

        btnExport.setText("Export Files");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbCurrent)
                                        .addComponent(rbAlt)
                                        .addComponent(btnExport))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbCurrent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbAlt)
                                .addGap(18, 18, 18)
                                .addComponent(btnExport)
                                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addGap(12, 12, 12)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnOpenFile)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(btnAbout, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(btnOpenFile)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1))
                                .addGap(25, 25, 25)
                                .addComponent(btnAbout)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>


    public void myInitComponents(){
        ButtonGroup group = new ButtonGroup();
        group.add(rbAlt);
        group.add(rbCurrent);

        btnOpenFile.addActionListener(new btnHandler());
        btnAbout.addActionListener(new btnHandler());
        btnExport.addActionListener(new btnHandler());
    }

    //public void create
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify
    private javax.swing.JButton btnAbout;
    private javax.swing.JTextArea areaInvalidList;
    private javax.swing.JTextArea areaMasterList;
    private javax.swing.JTextArea areaValidList;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rbAlt;
    private javax.swing.JRadioButton rbCurrent;
    private FileHandler fileHandler;
    private IPValidator ipValidator;
    // End of variables declaration
    
    private class btnHandler implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            if(e.getSource()==btnOpenFile)
            {
                try {
                    IPStorage.purgeLists();
                    areaMasterList.setText("");
                    areaInvalidList.setText("");
                    areaValidList.setText("");

                    fileHandler.openFile();
                    fileHandler.populateList();

                    for (int i = 0; i < IPStorage.getAddressList().size(); i++) {
                        areaMasterList.append(IPStorage.getAddressList().get(i) + "\n");
                    }

                    for(int i=0;i<IPStorage.getAddressList().size();i++) {
                        IPStorage.addValidatedIPAddress(IPStorage.getAddressList().get(i),ipValidator.IPcheck(IPStorage.getAddressList().get(i)));
                    }

                    for (int i=0;i<IPStorage.getValidatedList().size();i++){
                        if(IPStorage.getValidatedList().get(i).isValid())
                            areaValidList.append(IPStorage.getValidatedList().get(i).getIPAddress()+"\n");
                        else
                            areaInvalidList.append(IPStorage.getValidatedList().get(i).getIPAddress()+"\n");
                    }
                }
                catch (Exception ex)
                {}
            }
            if(e.getSource()==btnAbout)
                JOptionPane.showMessageDialog(null,"Ramoloi Lehlohonolo Justice Mofokeng\n email Addess:mofokengrlj@gmail.com");

            if(e.getSource()==btnExport) {
                if(!(rbCurrent.isSelected()) && !(rbAlt.isSelected()))
                    JOptionPane.showMessageDialog(null,"Please Select Current or Alternate Location to save the files");
                else
                    fileHandler.saveFIle(rbCurrent.isSelected());
                }
            }
        }
    }